dataset:
  root_path: '/home/zealot/zealot/RecSys/data/preprocessed/prepared'
  split:
    ratio: 0.9
    seed: 42
  posneg:
    neg_samples: 1

dataloader:
  batch_size: 256
  shuffle: True

model:
  GMF:
    user_dim: 6
    item_dim: 4
    latent_dim: 16
