dataset:
  root_path: '/home/zealot/zealot/RecSys/data/preprocessed/prepared'
  split:
    ratio: 0.8
    seed: 42
    val: 0.1
  posneg:
    neg_samples: 1

dataloader:
  batch_size: 256
  shuffle: True

model:
  GMF:
    user_dim: 6
    item_dim: 4
    latent_dim: 16

train:
  epochs: 10
  save: True
  save_epochs: 5
  save_path: './ckpt'
  lr: 0.001
